
# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'dbt_hackathon'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'default'

# These configurations specify where dbt should look for different types of files.
# The `source-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"


# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models
models:
  dbt_hackathon:
    pii:
      materialized: table
      database: HACKATHON
      schema: PII
    staging:
      coffee_shop:
        materialized: view

vars:
  pii_database: HACKATHON
  # Schema to evaluate:
  pii_schema: COFFEE_SHOP
  pii_exclude_tables: ('GENERATION', 'NEARBY_ZIPCODES', 'FIVETRAN_AUDIT')
  # Schema to store function and data:
  pii_results_schema: PII
  pii_probability_threshold: 0.7
  pii_rows_to_scan: 1000
  pii_warehouse: LOOKER_WH
  pii_execution_role: HACKATHON_ROLE
  pii_execution_role_users: ['JHUTH', 'ARAWAS', 'JSCHINTZ', 'RKHALIL', 'HKHARVA', 'LTA', 'RFREERCA', 'LOOKER_USER']
  pii_masking_roles: ['HACKATHON_MASKED_ROLE', 'HACKATHON_PARTIAL_ROLE', 'HACKATHON_HASHED_ROLE', 'HACKATHON_FAKER_ROLE']
  pii_masking_role_users: ['JHUTH', 'ARAWAS', 'JSCHINTZ', 'RKHALIL', 'HKHARVA', 'LTA', 'RFREERCA', 'LOOKER_USER']
  pii_unmasked_roles: ('SYSADMIN', 'HACKATHON_ROLE')
  pii_masked_roles: ('HACKATHON_MASKED_ROLE')
  pii_partial_roles: ('HACKATHON_PARTIAL_ROLE')
  pii_hashed_roles: ('HACKATHON_HASHED_ROLE')
  pii_faker_roles: ('HACKATHON_FAKER_ROLE')
  pii_ethnicity_arr: ['White/Caucasian/European American','Black/African American','Asian American','Native American','Hispanic/Latin American','Pacific Islander','Middle Eastern','Other','Multiple']
  pii_gender_arr: ['Male','Male','Male','Male','Female','Female','Female','Female','Transgender','Unspecified']
  pii_marital_status_arr: ['Single','Single','Single','Single','Married','Married','Married','Married','Widowed','Divorced','Divorced','Domestic Partnership','Unspecified']
